### ISSUE TITLE
Doing a rollback on safe_create_table fails

### ISSUE THREAD

**Issue by oniofchaos** [braintree/pg_ha_migrations#3]
Example migration file:
```
# db/migrate/20190124002047_create_jwt_blacklist.rb
class CreateJwtBlacklist < ActiveRecord::Migration[5.2]
  def change
    safe_create_table :jwt_blacklist do |t|
      t.string :jti, null: false
    end
  end
end
```

Error:
```
== 20190124002047 CreateJwtBlacklist: reverting ===============================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 2, expected 1)
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/pg_ha_migrations-0.2.0/lib/pg_ha_migrations/unsafe_statements.rb:28:in `drop_table'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:687:in `block in revert'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:686:in `each'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:686:in `revert'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:812:in `exec_migration'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/pg_ha_migrations-0.2.0/lib/pg_ha_migrations/safe_statements.rb:102:in `exec_migration'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:797:in `block in migrate'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:796:in `migrate'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:977:in `migrate'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `each'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1210:in `migrate'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1046:in `down'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1156:in `move'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:1022:in `rollback'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/railties/databases.rake:142:in `block (2 levels) in <main>'
/Users/dillonwelch/.rvm/rubies/ruby-2.6.1/bin/bundle:23:in `load'
/Users/dillonwelch/.rvm/rubies/ruby-2.6.1/bin/bundle:23:in `<main>'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
/Users/dillonwelch/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by JonMR** [comment]
Hey @oniofchaos, thanks for opening the issue and checking out the project.

This is actually something we've given thought to and have explicitly chosen not to tackle for a few reasons. Firstly, adding support for rollback would require the use of transactions. When modifying multiple objects, an exclusive lock will be acquired on all objects. This is something we try to avoid. In addition, not all DDL operations are safe to rollback. You need to have a keen awareness what the impacts of a rollback might be based on your application's usage patterns.

We've added some clarification to the [README](https://github.com/braintreeps/pg_ha_migrations#rollback). There's also a link to our blog there with further thoughts on transactionality in DDL.

I'm going to close the issue since this is not something we plan to support, but we're happy to follow up on any questions.

**Comment by oniofchaos** [comment]
Really appreciate the clarification to the README. What do you think about adding a user-friendly exception when `down` is executed with that same kind of explanation?

**Comment by JonMR** [comment]
That's a great idea. I'm going to just re-open this issue to implement that. Let me know if you're interested in PR'ing such a change so we don't duplicate any effort. :+1:

**Comment by oniofchaos** [comment]
I can at least take a look if you can point me in the right area where it makes sense to catch this issue.

**Comment by JonMR** [comment]
Happy to! We override the Rails [ActiveRecord::Migration#exec_migration](https://github.com/rails/rails/blob/v5.2.2/activerecord/lib/active_record/migration.rb#L808) to [check that the migrations are being run against Postgres](https://github.com/braintreeps/pg_ha_migrations/blob/v0.2.0/lib/pg_ha_migrations/safe_statements.rb#L100). 

After that check, you could add a similar check to ensure the migration doesn't implement `change`. You can probably re-use the existing `PgHaMigrations::InvalidMigrationError` exception as well.

Open to other ideas if you feel like there's a better approach.
